name: Go project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  format_test_and_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.13
          - 1.14
          - 1.15
          - 1.16
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check formatting
      run: sh -c ./scripts/gofmtcheck.sh

    - name: Run the tests
      run: go test -v ./redshift

    - name: Run errcheck
      run: make errcheck

    - name: Build
      run: go install
